apiVersion: v1
kind: Pod
metadata:
  name: empower-runtime
  labels:
    app: empower-runtime
spec:
  containers:
  - name: empower-runtime
    image: sensefbk/empower-runtime
    imagePullPolicy: Always


