apiVersion: v1
kind: Pod
metadata:
  name: srsenb
  labels:
    app: srsenb
spec:
  containers:
  - name: srsenb
    image: bytecommander12/srs-enb:test
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo waiting...; sleep 10; done"]
