# Minimal implementation of RAN
apiVersion: v1
kind: Pod
metadata:
  name: epc
  namespace: new-ns
  labels:
    app: epc
spec:
  containers:
  - name: open5gs
    image: snslab/open5gs:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: MCC
      value: "222"
    - name: MNC
      value: "93"
    - name: TAC
      value: "7"
    securityContext:
      privileged: true
  - name: open5gs-webui
    image: snslab/open5gs-webui:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000
  - name: mongodb
    image: mongo:4.4.6
    imagePullPolicy: IfNotPresent
  - name: mongo-express
    image: mongo-express
    imagePullPolicy: IfNotPresent
    env:
    - name: ME_CONFIG_MONGODB_SERVER
      value: localhost
