apiVersion: v1
kind: Pod
metadata:
  name: srsenb
  labels:
    app: srsenb
spec:
  containers:
  - name: srsenb
    image: bytecommander12/srs-enb:vm-test
    imagePullPolicy: Always
    env:
    - name: mcc
      value: "222"
    - name: mnc
      value: "93"
    - name: n_prb
      value: "50"
    - name: ipsec
      value: "yes"
    - name: empower_controller
      value: "no"
    securityContext:
      privileged: true
  - name: strongswan-ipsec
    image: bytecommander12/strongswan-epc-client:v1.0
    imagePullPolicy: Always
    env:
    - name: client_server_address
      value: upf-lb-service
    - name: client_server_id
      value: upf-lb
    - name: client_server_hostname
      value: "epc-service-pod"
    - name: client_client_ip
      value: "%config"
    - name: client_client_user
      value: enb-user
    - name: client_client_pass
      value: enb-pass
    securityContext:
      capabilities:
        add: ["NET_ADMIN","NET_RAW","SYS_ADMIN"]
