apiVersion: v1
kind: Pod
metadata:
  name: rnis-manager
  labels:
    app: rnis-manager
spec:
  containers:
  - name: rnis-manager
#    image: bytecommander12/lightedge-rnis:v1.0
    image: bytecommander12/rnis-manager:v1.0
    imagePullPolicy: Always
    command: ["/bin/bash"]
    args: ["-c","while true; do echo waiting; sleep 10; done"]
  - name: mongodb
    image: mongo:4.4.6
    imagePullPolicy: Always

