apiVersion: v1
kind: Pod
metadata:
  name: upf-2
  labels:
    app: upf
spec:
  containers:
  - name: upf
    image: bytecommander12/lightedge-upf-service:main-983419b
    imagePullPolicy: Always
    env:
    - name: mode
      value: upf
    - name: enbs_subnet
      value: "10.0.1.0/24"
    securityContext:
      capabilities:
        add: ["NET_ADMIN","NET_RAW","SYS_ADMIN"]
    command: ["/bin/bash"]
    args: ["-c","while true; do echo waiting; sleep 10; done"] 
  - name: upf-agent
    image: sensefbk/lightedge-upfservice-agent
    imagePullPolicy: IfNotPresent
  - name: mongodb
    image: mongo:4.4.6
    imagePullPolicy: IfNotPresent
  - name: influxdb
    image: influxdb
    imagePullPolicy: IfNotPresent
  - name: strongswan-ipsec
    image: bytecommander12/strongswan-epc-client:v1.0
    imagePullPolicy: Always
    env:
    - name: client_server_address
      value: epc-service
    - name: client_server_id
      value: epc
    - name: client_server_hostname
      value: "epc-service-pod"
    - name: client_client_subnet
      value: "10.0.1.0\\/24"
    - name: client_client_user
      value: upf-user
    - name: client_client_pass
      value: upf-pass
    securityContext:
      capabilities:
        add: ["NET_ADMIN","NET_RAW","SYS_ADMIN"]
  nodeSelector:
    disktype: cloud
---
apiVersion: v1
kind: Service
metadata:
  name: upf-service
spec:
  selector:
    app: upf-service
  type: NodePort
  ports:
  - name: udp-tunnel
    protocol: UDP
    port: 5555
    targetPort: 5555
  - name: upf-agent
    protocol: TCP
    port: 80
    targetPort: 80
